### ISSUE TITLE
ホーム画面のデザイン

### ISSUE THREAD

**Issue by sizuhiko** [its-succ/pong-swoosh#19]

**Comment by sizuhiko** [comment]
![untitled_page](https://user-images.githubusercontent.com/132000/120789992-500bf480-c56d-11eb-82d6-6bda9317822a.png)

**Comment by sizuhiko** [comment]
![_1](https://user-images.githubusercontent.com/132000/123775921-c3551c00-d909-11eb-841c-f2d9d80a5a7f.png)

**Comment by sizuhiko** [comment]
![_2](https://user-images.githubusercontent.com/132000/123775960-ccde8400-d909-11eb-9f15-0041d9fc384b.png)

**Comment by tastyHama** [comment]
アイコンあるとイメージ付きやすくていいですね
