### ISSUE TITLE
チャンネル作成者が効果音セットをカスタマイズできる

### ISSUE THREAD

**Issue by sizuhiko** [its-succ/pong-swoosh#49]
Herokuだとpostgresqlとか使った方が良いのかなぁ？
もうちょっと気軽にできると良いけど。

具体的な実装方針など未定

**Comment by sizuhiko** [comment]
候補を増やすためのネタとして、今音源を持ってきているサイト

https://soundeffect-lab.info/
https://vsq.co.jp/plus/

**Comment by minakamoto** [comment]
声系じゃなくて、ドラム系を以下らへんに変えるとか？
[ここの](https://soundeffect-lab.info/sound/anime/)
- 試合終了のゴング
- クイズ正解1
- ちゃんちゃん

**Comment by tastyHama** [comment]
あったら使いそう

https://soundeffect-lab.info/sound/various/various2.html
* 電子レンジ(チンベルの代わり)  🛎️ 
* 缶を開ける(宴会シーンで?) 🍺 

あとは笑い声1,2のバリエーション増やすとか？

**Comment by minakamoto** [comment]
声なら、使いどころはさておき、以下が気になりました

https://soundeffect-lab.info/sound/anime/

- 男衆「イヤッホー！」
- アヒルが大笑い

**Comment by sizuhiko** [comment]
> 缶を開ける(宴会シーンで?) 

注ぐ音まであるけど、こっちとかの方が音感は良いなー

https://on-jin.com/sound/index.php?kensaku=%E3%83%93%E3%83%BC%E3%83%AB

**Comment by tastyHama** [comment]
`注ぐ・炭酸飲料・缶` いいですね  👍🏾

**Comment by sizuhiko** [comment]
- チェンネル作成後画面で、URLの下にデフォルトで利用可能なボタン一覧を表示する
  - すべてのボタン一覧を返却するAPIを追加
  - チャンネル作成者のみ呼び出し可能
  - ボタン一覧にデフォルトフラグを追加
- ボタン一覧をカスタマイズするボタンを追加
  - ボタンをクリックするとポップアップする（試聴のモーダルっぽい感じ
  - 全ボタン一覧がチェックボックス付きで表示されて、デフォルトがチェック済みになっている
  - 最大8個までチェック可能
- チェックを変更して、保存する
  - 保存APIを追加
  - JSONもしくはRedisにチェック状態を保存
  - ボタンが変更されたことを、リスナー/コントローラへブロードキャスト
- 再接続時
  - チャンネルオーナーが再接続モードで接続するときは、再度保存APIを実行して、デフォルト状態を変更する

**Comment by sizuhiko** [comment]
ない効果音で、人の声とかだったら、GoogleのText-To-Speech で mp3 つくれるから、そういうのも活用しても良いかな
https://cloud.google.com/text-to-speech/?hl=ja
